### ISSUE TITLE
[BUG] issue using HC32 firmware - LCD restarts after using Save or M500

### ISSUE THREAD

**Issue by classicrocker883** [shadow578/framework-hc32f46x-ddl#2]
I believe the issue is related to one of the platforms framework or dll. I am able to compile and flash firmware in VS Code using platformio and everything seems to work fine except when Saving. Since this doesn't happen using the same source code with STM32F1 or GD32 or N32, I suspect it being something to do with the backend framework that is called by the _Hc32.ini_ or **Hc32f46x/HAL**.

its hard to trace the issue since I wouldn't know where to begin.

if you could please look into this.

**Comment by shadow578** [comment]
i assume you've since re-submitted this issue as https://github.com/shadow578/Marlin-H32/issues/37? I'll be closing this one then.

**Comment by classicrocker883** [comment]
yes thank you.
